"""Refresh numerical sections of the living report from results JSON.

Run after examples/run_all.py or examples/run_emulation.py. Those scripts call
this file so the tables track new results. A code change that alters physics,
the demo, or the reported numbers should also pass --append so the changelog
grows in the same commit.

    python examples/update_report.py
    python examples/update_report.py --append "what changed"
    python examples/update_report.py --check
"""
from __future__ import print_function

import datetime
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
REPORT = os.path.join(ROOT, "report")
DOCS_REPORT = os.path.join(ROOT, "docs", "report")


def _load(name):
    path = os.path.join(RES, name)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _tex_escape(text):
    out = []
    for ch in str(text):
        if ch == "\\":
            out.append("\\textbackslash{}")
        elif ch in ("&", "%", "$", "#", "_", "{", "}"):
            out.append("\\" + ch)
        elif ch == "~":
            out.append("\\textasciitilde{}")
        elif ch == "^":
            out.append("\\textasciicircum{}")
        else:
            out.append(ch)
    return "".join(out)


def _row(cells):
    return " & ".join(_tex_escape(c) for c in cells) + " \\\\"


def write_numbers():
    if not os.path.isdir(REPORT):
        os.makedirs(REPORT)
    D = _load("results.json")
    E = _load("emulation_compare.json")
    lines = []
    lines.append("% Auto-generated by examples/update_report.py. Do not edit by hand.")
    stamp = datetime.date.today().isoformat()
    lines.append("\\paragraph{Numerical tables regenerated %s.}" % stamp)
    if D is None:
        lines.append("Continuum results JSON was not present when this file was generated.")
    else:
        o = D["optimal"]
        b = D["baseline_pdf_initial_guess"]
        x = D["extra"]
        env = D["env"]
        lines.append("\\paragraph{Environment.} %s." % _tex_escape(
            ", ".join("%s %s" % (k, env[k]) for k in ("python", "numpy", "scipy", "numba", "matplotlib"))))
        lines.append("\\begin{center}\\begin{tabular}{lll}")
        lines.append("\\hline")
        lines.append(_row(["quantity", "PDF initial guess", "seed-1 optimum"]))
        lines.append("\\hline")
        pairs = [
            ("R1 [mm]", "%.2f" % (b["R1"] * 1e3), "%.2f" % (o["R1"] * 1e3)),
            ("R2 [mm]", "%.2f" % (b["R2"] * 1e3), "%.2f" % (o["R2"] * 1e3)),
            ("L [mm]", "%.1f" % (b["L"] * 1e3), "%.1f" % (o["L"] * 1e3)),
            ("current [A]", "%.1f" % b["I_A"], "%.1f" % o["I_A"]),
            ("voltage [V]", "%.3f" % b["V_total_V"], "%.3f" % o["V_total_V"]),
            ("electrical power [kW]", "%.3f" % (b["P_elec_W"] / 1e3), "%.3f" % (o["P_elec_W"] / 1e3)),
            ("hot-spot copper [C]", "%.3f" % b["T_hot_C"], "%.3f" % o["T_hot_C"]),
            ("homogeneity [ppm]", "%.2f" % b["homogeneity_ppm"], "%.2f" % o["homogeneity_ppm"]),
            ("flow [L/min]", "%.1f" % b["flow_L_min"], "%.1f" % o["flow_L_min"]),
            ("copper mass [kg]", "%.0f" % b["mass_cu_kg"], "%.0f" % o["mass_cu_kg"]),
        ]
        for row in pairs:
            lines.append(_row(row))
        lines.append("\\hline")
        lines.append("\\end{tabular}\\end{center}")
        lines.append(
            "Optimiser: %s, %s evaluations, %.0f s. "
            "Published pump-failure time to 85 C at the optimum is %.0f s. "
            "Hoop stress from the field profile is %.4f MPa. "
            "Heuristic Swiss-roll SNR gain is %.3f. Static permeability is 1."
            % (_tex_escape(D["optimiser"]["method"]), D["optimiser"]["de_nfev"], D["optimiser"]["seconds"],
               x["pump_failure_time_to_85C_s"], x["hoop_stress_max_MPa_profile"],
               x["swissroll"]["snr_gain_best"]))
    if E is None:
        lines.append("\\paragraph{Emulation.} results/emulation\\_compare.json was absent.")
    else:
        lines.append("\\paragraph{Mesoscopic emulation, not molecular dynamics.}")
        lines.append("Seed %s, %s realizations. %s" % (E["seed"], E["n_realizations"], _tex_escape(E["label"])))
        lines.append("\\begin{center}\\begin{tabular}{lrrrr}")
        lines.append("\\hline")
        lines.append(_row(["quantity", "nominal", "p05", "p50", "p95"]))
        lines.append("\\hline")
        nom = E["nominal_summary"]
        order = [
            ("B0 [T]", "B0_T", "%.6f"),
            ("V [V]", "V_V", "%.4f"),
            ("P [W]", "P_W", "%.1f"),
            ("T hot [C]", "T_hot_C", "%.4f"),
            ("ppm", "ppm", "%.3f"),
            ("drift [m/s]", "v_d_m_s", "%.6e"),
            ("mean free path [m]", "mean_free_path_m", "%.6e"),
            ("Johnson [V]", "V_johnson_V", "%.6e"),
        ]
        for label, key, fmt in order:
            p = E["percentiles"][key]
            lines.append(_row([label, fmt % nom[key], fmt % p["p05"], fmt % p["p50"], fmt % p["p95"]]))
        lines.append("\\hline")
        lines.append("\\end{tabular}\\end{center}")
        tr = E.get("trip_probability", {})
        lines.append("Trip fractions: hot spot above 85~C = %s, ONB margin below 0 = %s, stress above 0.6 yield = %s."
                     % (tr.get("T_hot_above_85C"), tr.get("onb_margin_below_0"), tr.get("stress_above_0.6_yield")))
        pf = E.get("pump_failure", {})
        if pf:
            lines.append(_tex_escape(pf.get("note", "")))
            lines.append(" PDF-guess adiabatic time to saturation in that file: %s s." % pf.get("time_to_tsat_s"))
    text = "\n".join(lines) + "\n"
    path = os.path.join(REPORT, "generated_numbers.tex")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


def append_changelog(message):
    stamp = datetime.date.today().isoformat()
    block = (
        "\\paragraph{%s.}\n%s\n\n" % (stamp, _tex_escape(message))
    )
    path = os.path.join(REPORT, "changelog.tex")
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(block)
    md = os.path.join(ROOT, "PROJECT_REPORT.md")
    with open(md, "a", encoding="utf-8") as fh:
        fh.write("\n### %s\n\n%s\n" % (stamp, message))
    return path


def sync_docs():
    if not os.path.isdir(DOCS_REPORT):
        os.makedirs(DOCS_REPORT)
    for name in ("bitter_solenoid_report.tex", "generated_numbers.tex", "changelog.tex",
                 "measured_validation.tex"):
        src = os.path.join(REPORT, name)
        if os.path.isfile(src):
            shutil.copyfile(src, os.path.join(DOCS_REPORT, name))
    src_md = os.path.join(ROOT, "PROJECT_REPORT.md")
    if os.path.isfile(src_md):
        shutil.copyfile(src_md, os.path.join(ROOT, "docs", "PROJECT_REPORT.md"))


def check():
    num = open(os.path.join(REPORT, "generated_numbers.tex"), encoding="utf-8").read()
    log = open(os.path.join(REPORT, "changelog.tex"), encoding="utf-8").read()
    tex = open(os.path.join(REPORT, "bitter_solenoid_report.tex"), encoding="utf-8").read()
    md = open(os.path.join(ROOT, "PROJECT_REPORT.md"), encoding="utf-8").read()
    required = ["17.974", "19.537", "21.153", "11.704", "4.543", "25.946", "99.95", "4922"]
    for token in required:
        if token not in num and token not in md:
            raise SystemExit("missing published figure %s" % token)
    if "generated_numbers" not in tex or "changelog" not in tex:
        raise SystemExit("main tex does not input the generated sections")
    if "mesoscopic emulation, not molecular dynamics" not in md.lower() and "Mesoscopic emulation" not in md:
        raise SystemExit("report label missing")
    if "Pages demo" not in log and "pages demo" not in log.lower():
        raise SystemExit("changelog has no Pages demo entry")
    docs_md = os.path.join(ROOT, "docs", "PROJECT_REPORT.md")
    if not os.path.isfile(docs_md):
        raise SystemExit("docs/PROJECT_REPORT.md missing")
    print("report check ok")


def main(argv):
    append = None
    if "--append" in argv:
        i = argv.index("--append")
        append = argv[i + 1]
    if "--check" in argv:
        # read-only: tests must not rewrite tracked files
        check()
        return
    write_numbers()
    if append:
        append_changelog(append)
    sync_docs()
    print("updated report numbers")


if __name__ == "__main__":
    main(sys.argv[1:])
